site_name: GIS Blog
theme: material

extra:
  logo: 'images/profile.png'
  palette:
    primary: 'red'
    accent: 'red'
  social:
    - type: 'github'
      link: 'https://github.com/HerbFargus'
    - type: 'twitter'
      link: 'https://twitter.com/fargusherb'

extra_css:
  - 'stylesheets/extra.css'

repo_name: 'GIS-Blog'
repo_url: 'https://github.com/HerbFargus/GIS-Blog'

copyright: 'Copyright &copy; 2017 Herb Fargus'
      
pages:
- Home: index.md
- Arcmap:
    - Arcmap EMF Files: ArcMap-EMF-files.md
    - Converting Degrees to Decimals: Converting-Degrees-to-Decimals.md
    - Converting Serial Dates: Converting-Serial-dates-to-MM-DD-YYYY.md
    - Importing Lat Long: Importing-Points-with-Latitude-and-Longitude.md
    - Query Table: Make-Query-Table.md
    - Parsing KML HTML Tables: Parsing-KML-HTML-Tables.md
    - Select By Attributes: Select-By-Attributes.md
    - Select By Location: Select-By-Location.md
    - Spatial Join: Spatial-Join.md
    - Table to Relationship Class: Table-to-Relationship-Class.md
- Field Calculator (Python):
    - If Then Statements: Field-Calculator-Python-If-Then-Statements.md
    - Joining and Concatenation: Field-Calculator-Python-Joining-Concatenation.md
    - Slicing: Field-Calculator-Python-Slicing.md
    - String Manipulation: Field-Calculator-Python-String-Manipulation.md
- Parcel Fabrics:
    - COGO: COGO.md
    - COGO Tools Drawing Lines: COGO-Tools:-Drawing-Lines.md
    - COGO Tools Labeling Lines: COGO-Tools:-Labeling-Lines.md
    - Creating a Parcel Fabric: Creating-a-Parcel-Fabric-from-Polygons.md
    - Label Parcel Fabric: Labeling-a-Parcel-Fabric-with-the-Maplex-Engine.md
- QGIS:
    - Creating mbtiles with Qtiles: QGIS:-QTiles.md
    - Vector Tiles: Vector-Tiles.md
    - GDAL and OGR: GDAL-and-OGR.md


